### ISSUE TITLE
error

### ISSUE THREAD

**Issue by StudyCat404** [alienwithin/xanity-php-rat#1]
![untitled](https://cloud.githubusercontent.com/assets/8930304/19211292/e39ea22a-8d45-11e6-8930-f6b14606a58c.png)
there is a mistake.

**Comment by alienwithin** [comment]
Try recompile from the source provided,

**Comment by roller743** [comment]
When I try to build the source in visual studio the build fails and says there are 41 errors. Why is this?

**Comment by alienwithin** [comment]
2 questions which version of visual studio and .net are u using and 2 what are the exact errors?

**Comment by roller743** [comment]
Here are the errors: https://pastebin.com/fgXyfCrk

And here is a screencap of the visual studio version, .NET version and also the target version. https://gyazo.com/3d728bb67029a5636eb0a30be6834474

**Comment by alienwithin** [comment]
well first things first ur dot net is relatively newer this was done with .net 4 on vs 2010; it would take a bit of work to port it to conform to ur environment abit will send u a how to.

**Comment by roller743** [comment]
So how can I do it?

**Comment by alienwithin** [comment]
try compiling it with .net 4.0 :-)
