### ISSUE TITLE
Broke

### ISSUE THREAD

**Issue by cyclo-techtwister** [alienwithin/xanity-php-rat#3]
Does not compile new client app is Broke

**Comment by alienwithin** [comment]
Please share the error. last i checked it does compile with minor warnings. :-)

**Comment by cyclo-techtwister** [comment]
@alienwithin First so you know, I tried using the following to compile:
VS2013 VS2015 VS2017 None would compile and reported numerous errors (100+) I will take a closer look and see if the issue is on my end and if I need to install a resource or other. OK, looks like I need Visual Basic .Net 2010 to compile..
